checking api key read

diff --git a/.github/workflows/build-deploy.yaml b/.github/workflows/build-deploy.yaml
--- a/.github/workflows/build-deploy.yaml
+++ b/.github/workflows/build-deploy.yaml
@@ -4,6 +4,8 @@ on: [push]
 jobs:
   build-deploy:
     runs-on: ubuntu-latest
+    env:
+      MAPBOX_KEY: ${{ secrets.MAPBOX_API_KEY }}
     permissions:
       contents: write  # Grants permission to push code to the repository
     steps:
@@ -13,10 +15,21 @@ jobs:
       - name: install dependencies
         run: npm install
 
+      - name: Verify Secret Exists and is Non-Empty
+        run: |
+          if [ -z "$MAPBOX_KEY" ]; then
+            echo "Error: MAPBOX_KEY is empty or not injected!"
+            exit 1
+          else
+            echo "Success: MAPBOX_KEY is injected."
+            # Check length instead of printing the secret value
+            echo "Secret character count: ${#MAPBOX_KEY}"
+          fi
+
       - name: build app
         run: npm run build
         env:
-          APP_SECRET: ${{ secrets.MAPBOX_API_KEY }} 
+          APP_SECRET: ${{ secrets.MAPBOX_API_KEY }}
 
       - name: Deploy to GitHub Pages 🚀
         uses: JamesIves/github-pages-deploy-action@v4
